
# Personalised tutor

This chapter will teach you how to use AI as a personalised tutor to explain concepts and functions you're struggling to understand, or would like more information on.

It will be helpful to work through these activities with a specific chapter of your course in mind (e.g., [Applied Data Skills](https://psyteachr.github.io/ads-v3/) week 1 or 2)

## Set-up

The key to maximising the usefulness of AI is to use prompt engineering to tailor the output your to your exact needs. Before you ask any questions, you need to tell the AI who you are and exactly how it should act.

Here's some examples:

> Act as an expert tutor for the programming language R. I am a learner on an Upskilling course "Applied Data Skills" and I am learning R for the first time. I work in the NHS in Health Informatics. I have never learned a programming language before. I have used Excel and SPSS. I have reasonably good general computer literacy. I will ask you questions about concepts and functions I do not understand based on my course materials. Always give me concrete examples when you provide an answer. Tailor your responses to my level of expertise. I am using R and RStudio on a Mac and the course will strongly use the tidyverse.

> Act as an expert tutor for the programming language R. I am a first year psychology student at the University of Glasgow and I am learning R for the first time. I have never learned a programming language before and I am not very confident with computers and I am anxious about learning programming. I have a Windows laptop. I will ask you questions about concepts and functions I do not understand based on my course materials. Always give me concrete examples when you provide an answer. Tailor your responses to my level of expertise. I am using R and RStudio and the course will strongly use the tidyverse.

> Act as an expert tutor for the programming language R. I am a second year psychology student at the University of Glasgow. I have been learning R for a year. I also study statistics and computing science and know a bit of Python as well. I feel confident with learning to code and I would like to stretch myself. I will ask you questions about concepts and functions I do not understand based on my course materials. Always give me concrete examples when you provide an answer. Tailor your responses to my level of expertise. I am using R and RStudio and the course will strongly use the tidyverse although I would also like to learn about base R alternative approaches.

## Activity 1: Write your set-up {#sec-setup}

Write your set-up. It's worth spending some time to get this right, you're going to use it a lot.

I'd probably recommend using ChatGPT or Gemini for this because it's helpful to be able to save your chat and the set-up information. You could also use a personal Copilot account but the Enterprise version won't save your chats. If you'd like to use Copilot, save your set-up prompt somewhere to make it easy to reuse.

Exactly what information you provide is up to you but make sure that you explain your level of knowledge, skill, confidence and previous experience. By specifying what your field is (psychology, NHS etc.) it can then give you examples related to these fields which will make it easier for you to understand and connect your new knowledge to existing knowledge. Finally, you also want to give it some technical information about the software you're using (e.g., R and RStudio) and your operating system (Windows).

## Activity 2: Instruct the AI

Enter your set-up into a new chat on your AI of choice. If you're using an AI that saves your chats, you could also rename the chat to "Personal R Tutor" or "Week 1 Tutor" or anything else that make sense to you. Depending on what information you give it, it may give you some intro to R tips and information which may be more or less useful, so if you're new and it's confusing, just ignore it.

## Example questions

Now that you've got your tutor set up, you can ask it questions. Here's some examples:

* Why do I have to learn to code?
* What is the difference between a function and an argument?
* Explain what each part of this code is doing: `ggplot(survey_data, aes(x = wait_time, y = call_time)) +  geom_point()`
* Give me examples of when I would use different joins

## Activity 3: Questions

Ask the AI three questions based on your course materials. If the output doesn't seem at the right level for you, consider editing your initial set-up prompt and re-running the questions to see how the output changes.


## Follow-up

Another big difference between AI and a regular search engine is that you can have a conversation with it and follow-up on your original question. Some examples:

* Can you explain it again but compare it to Excel?
* Expand on your explanation of `geom_point()`
* Give me another example of code that uses this approach
* Explain it again but in more technical / simpler terms (Gemini's modify response can also be used for this)
* Ask me a question to test if I understand this correctly (we're going to go into practice testing a lot more in the next chapter)
* In your answer you said "In this example, c() is a function that combines values into a vector", what is a vector?

## Activity 4: Follow-up

Ask a follow-up question to each of your original questions. Additionally, try out the features of each AI. For Gemini, use the modify response and double-check response options. For ChatGPT, use regenerate response. For Copilot, click on the suggested follow-up questions or any links it provides.


::: {.callout-caution, "Feedback"}
This book should be considered a **living document** and is likely to change over time. Given the brave new world in which we now live, all constructive feedback and suggestions are welcome! If you have any feedback or suggestions, please provide it [via Forms](https://forms.office.com/Pages/ResponsePage.aspx?id=KVxybjp2UE-B8i4lTwEzyKAHhjrab3lLkx60RR1iKjNUM0VCMUUxUUFLMTdNM0JTS09PSDg2SFQ3US4u).
:::



