# Overview {.unnumbered}

This book aims to teach students how to use AI to support their learning journey. The philosophy of this book is firmly rooted in the cognitive science of learning and as such, retrieval practice, distributed practice, and elaboration will all play a key role.

It is perhaps easier to start by explaining what this book is not:

* This book **is not a stand-alone resource**. It is intended to be used alongside other course materials. To make the most out of this book, you will need things like Intended Learning Outcomes, ma
* This book **will not encourage learners to take short-cuts**. That students should be able to understanding the principles of what they are learning and to critically evaluate writing on the topic, regardless of who or what wrote it, is non-negotiable.
* For the coding aspects of this book, we will not not teach you how to use platforms like Github Copilot and it **is not aimed at proficient or advanced programmers**. 

Instead, this book will aim to help learners use AI platforms as a personalised tutor. By the end of this book, learners should be able to:

* Use AI to explain concepts and functions in a level of detail and technicality appropriate to the knowledge and skill of the learner
* Use AI to generate practice questions to test understanding
* Use AI to debug errors in code
* Use AI to review, comments, and refactor code
* Use AI to **responsibly** assist with writing code
* Use AI to create study plans
* Critically evaluate and appraise the output of AI

::: {.callout-warning}
Using AI to write code is the final part of the coding section, and that is an intentional choice. Using AI can superpower your coding but only once you have a solid foundation of knowledge. You need to be able to evaluate what it produces and you need to know what to ask it with enough specificity. Using AI to write code you don't understand is as dangerous as it is irresponsible.
:::

::: {.callout-caution}
This book should be considered a **living document** and is likely to change over time. Given the brave new world in which we now live, all constructive feedback and suggestions are welcome! If you have any feedback or suggestions, please provide it [via Forms](https://forms.office.com/Pages/ResponsePage.aspx?id=KVxybjp2UE-B8i4lTwEzyKAHhjrab3lLkx60RR1iKjNUM0VCMUUxUUFLMTdNM0JTS09PSDg2SFQ3US4u).
:::
